# -- Servo Configuration --
SERIAL_PORT = "/dev/cu.usbmodem58760433931"  
BAUD_RATE = 1000000  
SERVO_IDS = [1, 2, 3, 4, 5, 6]  

# -- Feetech Servo Address Map --
ADDR_TORQUE_ENABLE = 40
ADDR_GOAL_POSITION = 42
ADDR_PRESENT_POSITION = 56
ADDR_PRESENT_SPEED = 60
ADDR_PRESENT_VOLTAGE = 62
ADDR_PRESENT_TEMPERATURE = 63
ADDR_GOAL_ACC = 41
ADDR_GOAL_SPEED = 46
ADDR_MIDPOINT_OFFSET = 20

# -- Recording & Replay Settings --
RECORDING_DURATION = 10 
SAMPLING_INTERVAL = 0.1 
VIDEO_FPS = round(1.0 / SAMPLING_INTERVAL)
RECORDINGS_FOLDER = "recordings" # Folder to save recordings
REST_POSITIONS_FILENAME = "rest_positions.json"
MOVEMENT_FILENAME_TEMPLATE = "{}_{}.csv"
VIDEO_FILENAME_TEMPLATE = "{}_{}.mp4"

# -- Video Settings --
VIDEO_SOURCE = 0  # 0 for the default webcam
VIDEO_FRAME_WIDTH = 640
VIDEO_FRAME_HEIGHT = 480
